create extension if not exists pg_trgm with schema public;

create table if not exists public.rawi_aliases (
  id bigint generated by default as identity primary key,
  rawi_id bigint not null references public.rawis(id) on delete cascade,
  alias text not null,
  alias_type text,
  created_at timestamp with time zone default now(),
  unique (rawi_id, alias)
);

do $$
begin
  if exists (
    select 1
    from public.hadith
    where type is not null
      and type not in ('main', 'sub', 'part', 'h_main', 'h_part')
  ) then
    raise exception 'Cannot narrow hadith.type constraint: legacy type values still exist';
  end if;
end $$;

alter table public.hadith
  drop constraint if exists hadith_type_check;

alter table public.hadith
  add constraint hadith_type_check
  check (type = any (array['main'::text, 'sub'::text, 'part'::text, 'h_main'::text, 'h_part'::text]));

create index if not exists idx_books_volume_order on public.books (volume_id, order_index, id);
create index if not exists idx_chapters_book_order on public.chapters (book_id, order_index, id);
create index if not exists idx_hadith_chapter_order on public.hadith (chapter_id, order_index, id);
create index if not exists idx_hadith_type on public.hadith (type);
create index if not exists idx_hadith_rawi_rawi_hadith on public.hadith_rawi (rawi_id, hadith_id);
create index if not exists idx_hadith_rawi_hadith_rawi on public.hadith_rawi (hadith_id, rawi_id);
create index if not exists idx_hadith_normalized_trgm on public.hadith using gin ((public.normalize_ar(text)) public.gin_trgm_ops);
create index if not exists idx_rawis_normalized_trgm on public.rawis using gin ((public.normalize_ar(name)) public.gin_trgm_ops);
create index if not exists idx_rawi_aliases_rawi on public.rawi_aliases (rawi_id);
create index if not exists idx_rawi_aliases_normalized_trgm on public.rawi_aliases using gin ((public.normalize_ar(alias)) public.gin_trgm_ops);

create or replace function public.app_get_filter_tree()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'volumes', coalesce((
      select jsonb_agg(jsonb_build_object('id', v.id, 'name', v.name, 'order_index', v.order_index) order by v.order_index, v.id)
      from public.volumes v
    ), '[]'::jsonb),
    'books', coalesce((
      select jsonb_agg(jsonb_build_object('id', b.id, 'volume_id', b.volume_id, 'name', b.name, 'order_index', b.order_index) order by b.order_index, b.id)
      from public.books b
    ), '[]'::jsonb),
    'chapters', coalesce((
      select jsonb_agg(jsonb_build_object('id', c.id, 'book_id', c.book_id, 'name', c.name, 'order_index', c.order_index) order by c.order_index, c.id)
      from public.chapters c
    ), '[]'::jsonb)
  );
$$;

create or replace function public.app_search_hadith(
  p_query text default null,
  p_volume_ids bigint[] default null,
  p_book_ids bigint[] default null,
  p_chapter_ids bigint[] default null,
  p_types text[] default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  text_html text,
  hadith_type text,
  page_number integer,
  takhreej text,
  takhreej_full text,
  chapter_id bigint,
  chapter_name text,
  book_id bigint,
  book_name text,
  volume_id bigint,
  volume_name text,
  volume_order integer,
  book_order integer,
  chapter_order integer,
  hadith_order integer,
  narrators text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.hadith_number,
    h.text,
    h.text_html,
    h.type,
    h.page_number,
    h.takhreej,
    h.takhreej_full,
    c.id,
    c.name,
    b.id,
    b.name,
    v.id,
    v.name,
    v.order_index,
    b.order_index,
    c.order_index,
    h.order_index,
    coalesce(string_agg(distinct r.name, '، ' order by r.name), '') as narrators
  from public.hadith h
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  left join public.hadith_rawi hr on hr.hadith_id = h.id
  left join public.rawis r on r.id = hr.rawi_id
  where (p_query is null or btrim(p_query) = '' or public.normalize_ar(h.text) ilike '%' || public.normalize_ar(p_query) || '%')
    and (p_volume_ids is null or cardinality(p_volume_ids) = 0 or v.id = any(p_volume_ids))
    and (p_book_ids is null or cardinality(p_book_ids) = 0 or b.id = any(p_book_ids))
    and (p_chapter_ids is null or cardinality(p_chapter_ids) = 0 or c.id = any(p_chapter_ids))
    and (p_types is null or cardinality(p_types) = 0 or h.type = any(p_types))
  group by h.id, c.id, b.id, v.id
  order by v.order_index, b.order_index, c.order_index, h.order_index, h.id
  limit greatest(1, least(coalesce(p_limit, 50), 500))
  offset greatest(0, coalesce(p_offset, 0));
$$;

create or replace function public.app_get_hadith_index(
  p_volume_ids bigint[] default null,
  p_book_ids bigint[] default null,
  p_chapter_ids bigint[] default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  hadith_id bigint,
  hadith_number text,
  hadith_beginning text,
  hadith_type text,
  chapter_name text,
  book_name text,
  volume_name text,
  hadith_order integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.hadith_number,
    array_to_string((regexp_split_to_array(btrim(h.text), '\s+'))[1:15], ' ')
      || case when array_length(regexp_split_to_array(btrim(h.text), '\s+'), 1) > 15 then '...' else '' end,
    h.type,
    c.name,
    b.name,
    v.name,
    h.order_index
  from public.hadith h
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  where h.type in ('main', 'sub', 'part', 'h_main', 'h_part')
    and (p_volume_ids is null or cardinality(p_volume_ids) = 0 or v.id = any(p_volume_ids))
    and (p_book_ids is null or cardinality(p_book_ids) = 0 or b.id = any(p_book_ids))
    and (p_chapter_ids is null or cardinality(p_chapter_ids) = 0 or c.id = any(p_chapter_ids))
  order by v.order_index, b.order_index, c.order_index, h.order_index, h.id
  limit greatest(1, least(coalesce(p_limit, 100), 1000))
  offset greatest(0, coalesce(p_offset, 0));
$$;

create or replace function public.app_search_rawis(
  p_query text default null,
  p_limit integer default 20
)
returns table (
  rawi_id bigint,
  rawi_name text,
  matched_alias text,
  match_source text
)
language sql
stable
security definer
set search_path = public
as $$
  with matches as (
    select r.id as rawi_id, r.name as rawi_name, null::text as matched_alias, 'name'::text as match_source
    from public.rawis r
    where p_query is null or btrim(p_query) = '' or public.normalize_ar(r.name) ilike '%' || public.normalize_ar(p_query) || '%'
    union
    select r.id, r.name, a.alias, coalesce(a.alias_type, 'alias')
    from public.rawis r
    join public.rawi_aliases a on a.rawi_id = r.id
    where p_query is not null and btrim(p_query) <> ''
      and public.normalize_ar(a.alias) ilike '%' || public.normalize_ar(p_query) || '%'
  )
  select distinct on (rawi_id, coalesce(matched_alias, '')) rawi_id, rawi_name, matched_alias, match_source
  from matches
  order by rawi_id, coalesce(matched_alias, ''), rawi_name
  limit greatest(1, least(coalesce(p_limit, 20), 100));
$$;

create or replace function public.app_get_rawi_hadiths(
  p_rawi_ids bigint[] default null,
  p_volume_ids bigint[] default null,
  p_book_ids bigint[] default null,
  p_chapter_ids bigint[] default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  rawi_id bigint,
  rawi_name text,
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  hadith_type text,
  chapter_name text,
  book_name text,
  volume_name text,
  hadith_order integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id,
    r.name,
    h.id,
    h.hadith_number,
    h.text,
    h.type,
    c.name,
    b.name,
    v.name,
    h.order_index
  from public.rawis r
  join public.hadith_rawi hr on hr.rawi_id = r.id
  join public.hadith h on h.id = hr.hadith_id
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  where (p_rawi_ids is null or cardinality(p_rawi_ids) = 0 or r.id = any(p_rawi_ids))
    and (p_volume_ids is null or cardinality(p_volume_ids) = 0 or v.id = any(p_volume_ids))
    and (p_book_ids is null or cardinality(p_book_ids) = 0 or b.id = any(p_book_ids))
    and (p_chapter_ids is null or cardinality(p_chapter_ids) = 0 or c.id = any(p_chapter_ids))
  order by r.name, v.order_index, b.order_index, c.order_index, h.order_index, h.id
  limit greatest(1, least(coalesce(p_limit, 100), 1000))
  offset greatest(0, coalesce(p_offset, 0));
$$;

create or replace function public.app_get_narrator_musnad(
  p_narration_count integer default 1,
  p_volume_ids bigint[] default null,
  p_book_ids bigint[] default null,
  p_chapter_ids bigint[] default null,
  p_limit integer default 200,
  p_offset integer default 0
)
returns table (
  rawi_id bigint,
  rawi_name text,
  narration_count bigint,
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  hadith_type text,
  chapter_name text,
  book_name text,
  volume_name text
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as (
    select hr.rawi_id, count(distinct hr.hadith_id) as narration_count
    from public.hadith_rawi hr
    join public.hadith h on h.id = hr.hadith_id
    join public.chapters c on c.id = h.chapter_id
    join public.books b on b.id = c.book_id
    join public.volumes v on v.id = b.volume_id
    where (p_volume_ids is null or cardinality(p_volume_ids) = 0 or v.id = any(p_volume_ids))
      and (p_book_ids is null or cardinality(p_book_ids) = 0 or b.id = any(p_book_ids))
      and (p_chapter_ids is null or cardinality(p_chapter_ids) = 0 or c.id = any(p_chapter_ids))
    group by hr.rawi_id
    having count(distinct hr.hadith_id) = coalesce(p_narration_count, 1)
  )
  select
    r.id,
    r.name,
    f.narration_count,
    h.id,
    h.hadith_number,
    h.text,
    h.type,
    c.name,
    b.name,
    v.name
  from filtered f
  join public.rawis r on r.id = f.rawi_id
  join public.hadith_rawi hr on hr.rawi_id = r.id
  join public.hadith h on h.id = hr.hadith_id
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  where (p_volume_ids is null or cardinality(p_volume_ids) = 0 or v.id = any(p_volume_ids))
    and (p_book_ids is null or cardinality(p_book_ids) = 0 or b.id = any(p_book_ids))
    and (p_chapter_ids is null or cardinality(p_chapter_ids) = 0 or c.id = any(p_chapter_ids))
  order by f.narration_count desc, r.name, v.order_index, b.order_index, c.order_index, h.order_index
  limit greatest(1, least(coalesce(p_limit, 200), 1000))
  offset greatest(0, coalesce(p_offset, 0));
$$;

create or replace function public.app_get_single_hadith_details(p_hadith_id bigint)
returns table (
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  hadith_text_html text,
  hadith_type text,
  short_takhreej text,
  long_takhreej text,
  chapter_name text,
  book_name text,
  volume_id bigint,
  volume_name text,
  narrators text,
  hadith_order_index integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.hadith_number,
    h.text,
    h.text_html,
    h.type,
    h.takhreej,
    h.takhreej_full,
    c.name,
    b.name,
    v.id,
    v.name,
    coalesce(string_agg(distinct r.name, '، ' order by r.name), '') as narrators,
    h.order_index
  from public.hadith h
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  left join public.hadith_rawi hr on hr.hadith_id = h.id
  left join public.rawis r on r.id = hr.rawi_id
  where h.id = p_hadith_id
  group by h.id, c.id, b.id, v.id;
$$;

create or replace function public.app_get_hadith_context(p_hadith_id bigint)
returns table (
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  text_html text,
  hadith_type text,
  page_number integer,
  takhreej text,
  takhreej_full text,
  chapter_name text,
  book_name text,
  volume_id bigint,
  volume_name text,
  narrators text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.hadith_number,
    h.text,
    h.text_html,
    h.type,
    h.page_number,
    h.takhreej,
    h.takhreej_full,
    c.name,
    b.name,
    v.id,
    v.name,
    coalesce(string_agg(distinct r.name, '، ' order by r.name), '') as narrators
  from public.hadith h
  join public.chapters c on c.id = h.chapter_id
  join public.books b on b.id = c.book_id
  join public.volumes v on v.id = b.volume_id
  left join public.hadith_rawi hr on hr.hadith_id = h.id
  left join public.rawis r on r.id = hr.rawi_id
  where h.id = p_hadith_id
  group by h.id, c.id, b.id, v.id;
$$;

create or replace function public.app_browse_content(
  p_volume_id bigint default null,
  p_book_id bigint default null,
  p_chapter_id bigint default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  hadith_id bigint,
  hadith_number text,
  hadith_text text,
  text_html text,
  hadith_type text,
  page_number integer,
  takhreej text,
  takhreej_full text,
  chapter_id bigint,
  chapter_name text,
  book_id bigint,
  book_name text,
  volume_id bigint,
  volume_name text,
  volume_order integer,
  book_order integer,
  chapter_order integer,
  hadith_order integer,
  narrators text
)
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.app_search_hadith(
    null,
    case when p_volume_id is null then null else array[p_volume_id] end,
    case when p_book_id is null then null else array[p_book_id] end,
    case when p_chapter_id is null then null else array[p_chapter_id] end,
    null,
    p_limit,
    p_offset
  );
$$;

grant execute on function public.app_get_filter_tree() to anon, authenticated;
grant execute on function public.app_search_hadith(text, bigint[], bigint[], bigint[], text[], integer, integer) to anon, authenticated;
grant execute on function public.app_get_hadith_index(bigint[], bigint[], bigint[], integer, integer) to anon, authenticated;
grant execute on function public.app_search_rawis(text, integer) to anon, authenticated;
grant execute on function public.app_get_rawi_hadiths(bigint[], bigint[], bigint[], bigint[], integer, integer) to anon, authenticated;
grant execute on function public.app_get_narrator_musnad(integer, bigint[], bigint[], bigint[], integer, integer) to anon, authenticated;
grant execute on function public.app_get_single_hadith_details(bigint) to anon, authenticated;
grant execute on function public.app_get_hadith_context(bigint) to anon, authenticated;
grant execute on function public.app_browse_content(bigint, bigint, bigint, integer, integer) to anon, authenticated;
